# Numpy Tutorial

In [ ]:
import numpy as np
import time

## Numpy 속도 테스트

In [ ]:
#test speed
def sum_trad():
    start = time.time()
    X = range(10000000)
    Y = range(10000000)
    Z = []
    for i in range(len(X)):
        Z.append(X[i] + Y[i])
    return time.time() - start
    
def sum_numpy():
    start = time.time()
    X = np.arange(10000000) 
    Y = np.arange(10000000) 
    Z=X+Y
    return time.time() - start

print ('time sum:',sum_trad(),'  time sum numpy:',sum_numpy())

time sum: 3.6502702236175537   time sum numpy: 0.060819387435913086


## 배열 생성

### 단일 값으로 초기화

In [ ]:
# 단일 값으로 초기화된 배열 생성
print(np.full((3, 3), np.inf))
print(np.full((3, 3), 10.1))

[[inf inf inf]
 [inf inf inf]
 [inf inf inf]]
[[10.1 10.1 10.1]
 [10.1 10.1 10.1]
 [10.1 10.1 10.1]]


In [ ]:
# 배열을 단일 값으로 리셋
arr = np.array([10, 20, 33], float)
print (arr)
arr.fill(1)
print (arr)

[10. 20. 33.]
[1. 1. 1.]


### 랜덤 초기화

In [ ]:
# 정수 순열로 초기화된 배열 생성
np.random.permutation(3)

array([1, 2, 0])

In [ ]:
# 정규분포로 초기화된 배열 생성
np.random.normal(0,1,5)

array([ 1.82814342, -0.02107179, -1.44546207, -1.31156305, -0.36894489])

In [ ]:
# 균등분포로 초기화된 배열 생성
np.random.random(5)

array([0.02013974, 0.8324721 , 0.8534163 , 0.45079965, 0.95015531])

#### 리스트에서 생성

In [ ]:
#리스트에서 배열 생성
arr = np.array([2, 6, 5, 9], float)
print (arr)
print (type(arr))

[2. 6. 5. 9.]
<class 'numpy.ndarray'>


In [ ]:
# 배열에서 리스트로 변환
arr = np.array([1, 2, 3], float)
print (arr.tolist())
print (list(arr))

[1.0, 2.0, 3.0]
[1.0, 2.0, 3.0]


### 배열 복사

In [ ]:
arr = np.array([1, 2, 3], float)
arr1 = arr
arr2 = arr.copy()
arr[0] = 0
print (arr)
print (arr1)
print (arr2)

[0. 2. 3.]
[0. 2. 3.]
[1. 2. 3.]


### 단위 행렬

In [ ]:
#단위 행렬 생성
print (np.identity(3, dtype=int))
print (np.identity(3))

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 대각 행렬

In [ ]:
#대각 행렬 생성
np.eye(3, k=1, dtype=float)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

### 영행렬, 1행렬

In [ ]:
print (np.zeros(6, dtype=int))
print (np.ones((2,3), dtype=float))

[0 0 0 0 0 0]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# 주어진 배열과 동일한 차원의 영행렬, 1행렬 생성
arr = np.array([[13, 32, 31], [64, 25, 76]], float)
print(np.zeros_like(arr))
print(np.ones_like(arr))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


### 배열 쌓기

In [ ]:
x = np.array([2, 3, 4]) 
y = np.array([3, 4, 5]) 
print(np.stack((x, y)))
print(np.stack((x, y), axis=-1))

[[2 3 4]
 [3 4 5]]
[[2 3]
 [3 4]
 [4 5]]


### 2차원 배열 랜덤 초기화

In [ ]:
# 균등분포로 초기화된 2차원 배열 생성
print (np.random.rand(2,3))

# 다변량 정규분포로 초기화된 2차원 배열 생성
print (np.random.multivariate_normal([10, 0], [[3, 1], [1, 4]], size=[5,]))

[[0.73446211 0.01714909 0.01587249]
 [0.57186708 0.6999267  0.50920115]]
[[10.74523772  0.39382103]
 [ 8.22230843 -1.15770236]
 [11.28082936  0.73575752]
 [ 9.51187689  0.70435558]
 [ 7.53202566  0.25500334]]


## 배열 관리

### 배열 읽기/쓰기

In [ ]:
arr = np.array([2., 6., 5., 5.])
print(arr[:3])
print(arr[3])
arr[0] = 5.
print(arr)

[2. 6. 5.]
5.0
[5. 6. 5. 5.]


### 중복 제거

In [ ]:
arr = np.array([2., 6., 5., 5.])
print(np.unique(arr))

[2. 5. 6.]


### 정렬/섞기

In [ ]:
# 정렬
print(np.sort(arr))

# 정렬해서 인덱스 배열 생성
print(np.argsort(arr))

# 랜덤하게 섞기
np.random.shuffle(arr)
print(arr)

# 배열 비교
print(np.array_equal(arr,np.array([1,3,2])))

[2. 5. 5. 6.]
[0 2 3 1]
[2. 6. 5. 5.]
False


### 배열 슬라이싱

In [ ]:
# 슬라이싱
matrix = np.array([[ 4., 5., 6.], [2, 3, 6]], float)
print(matrix)

arr = np.array([[ 4., 5., 6.], [ 2., 3., 6.]], float)
print(arr[1:2,2:3])
print(arr[1,:])
print(arr[:,2])
print(arr[-1:,-2:])

[[4. 5. 6.]
 [2. 3. 6.]]
[[6.]]
[2. 3. 6.]
[6. 6.]
[[3. 6.]]


### 1차원 배열로 펴기

In [ ]:
# Flattening
arr = np.array([[10, 29, 23], [24, 25, 46]], float)
print(arr)
print(arr.flatten())

[[10. 29. 23.]
 [24. 25. 46.]]
[10. 29. 23. 24. 25. 46.]


### 배열의 크기와 데이터 타입

In [ ]:
# 배열의 모양 확인
print(arr.shape)

# 데이터 타입 확인
print(arr.dtype)

# 데이터 타입 변환
int_arr = matrix.astype(np.int32)
print(int_arr)

(2, 3)
float64
[[4 5 6]
 [2 3 6]]


In [ ]:
# 1차원의 길이
arr = np.array([[ 4., 5., 6.], [ 2., 3., 6.]], float)
print(len(arr))

2


### 재배열

In [ ]:
# 배열의 재배열
arr = np.array(range(8), float)
print(arr)
arr = arr.reshape((4,2))
print(arr)
print(arr.shape)

[0. 1. 2. 3. 4. 5. 6. 7.]
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]]
(4, 2)


### 전치 행렬

In [ ]:
arr = np.array(range(6), float).reshape((2, 3))
print(arr)
print(arr.transpose())

[[0. 1. 2.]
 [3. 4. 5.]]
[[0. 3.]
 [1. 4.]
 [2. 5.]]


In [ ]:
# 행렬의 T 속성으로 전치하기
matrix = np.arange(15).reshape((3, 5))
print(matrix)
print(matrix .T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


### 차원 늘리기

In [ ]:
# newaxis로 차원 늘리기
arr = np.array([14, 32, 13], float)
print(arr)
print(arr[:,np.newaxis])
print(arr[:,np.newaxis].shape)
print(arr[np.newaxis,:])
print(arr[np.newaxis,:].shape)

[14. 32. 13.]
[[14.]
 [32.]
 [13.]]
(3, 1)
[[14. 32. 13.]]
(1, 3)


### 배열 결합

In [ ]:
arr1 = np.array([[11, 12], [32, 42]], float)
arr2 = np.array([[54, 26], [27, 28]], float)
print(np.concatenate((arr1,arr2)))

# 1차원 방향으로 결합
print(np.concatenate((arr1,arr2), axis=0))

# 2차원 방향으로 결합
print(np.concatenate((arr1,arr2), axis=1))

[[11. 12.]
 [32. 42.]
 [54. 26.]
 [27. 28.]]
[[11. 12.]
 [32. 42.]
 [54. 26.]
 [27. 28.]]
[[11. 12. 54. 26.]
 [32. 42. 27. 28.]]


### 문자열 변환

In [ ]:
# 배열에서 문자열로 변환
arr = np.array([10, 20, 30], float)
str = arr.tostring()
print(str)

#문자열에서 배열로 변환
print(np.fromstring(str))

b'\x00\x00\x00\x00\x00\x00$@\x00\x00\x00\x00\x00\x004@\x00\x00\x00\x00\x00\x00>@'
[10. 20. 30.]


C:\Users\Fermi_2\Anaconda3\envs\TensorFlow2.0\lib\site-packages\ipykernel_launcher.py:7: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  import sys


## 배열 연산

### 산술연산

In [ ]:
#array operations
arr1 = np.array([1,2,3], float)
arr2 = np.array([1,2,3], float)
print(arr1+arr2)
print(arr1-arr2)
print(arr1 * arr2)
print(arr2 / arr1)
print(arr1 % arr2)
print(arr2**arr1)

[2. 4. 6.]
[0. 0. 0.]
[1. 4. 9.]
[1. 1. 1.]
[0. 0. 0.]
[ 1.  4. 27.]


## 논리 연산

In [8]:
a1 =  np.array([
    [1, 2, 3],
    [4, 5, 6]
])
X1 = a1 % 2 == 0
X2 = a1 >= 4
X3 = X1*1
print(X1)
print(X2)
print(X3)

[[False  True False]
 [ True False  True]]
[[False False False]
 [ True  True  True]]
[[0 1 0]
 [1 0 1]]


In [ ]:
np.logical_and(X1, X2)

array([[False, False, False],
       [ True, False,  True]])

### 브로드캐스팅

In [ ]:
arr1 = np.zeros((2,2), float)
arr2 = np.array([1., 2.], float)

print(arr1)
print(arr2)
print(arr1 + arr2)

[[0. 0.]
 [0. 0.]]
[1. 2.]
[[1. 2.]
 [1. 2.]]


In [ ]:
# 인덱스 배열로 쿼리
arr1 = np.zeros((2,2), float)
arr2 = np.array([1., 2.], float)
print( arr1 + arr2[np.newaxis,:])
print(arr1 + arr2[:,np.newaxis])

[[1. 2.]
 [1. 2.]]
[[1. 1.]
 [2. 2.]]


### 배열 쿼리

In [ ]:
# 인덱스 배열로 쿼리
arr1 = np.array([1, 4, 5, 9], float)
arr2 = np.array([0, 1, 1, 3, 1, 1, 1], int)
print(arr1[arr2])

[1. 4. 4. 9. 4. 4. 4.]


array([13.,  2.,  1., 13.])

In [ ]:
# 다차원 배열 인덱스 배열로 쿼리
arr1 = np.array([[1, 2], [5, 13]], float)
arr2 = np.array([1, 0, 0, 1], int)
arr3 = np.array([1, 1, 0, 1], int)
arr1[arr2,arr3]

In [ ]:
# take 함수로 쿼리
arr1 = np.array([7, 6, 6, 9], float)
arr2 = np.array([1, 0, 1, 3, 3, 1], int)
arr1.take(arr2)

In [ ]:
# 차원에 따라 부분집합 선택
arr1 = np.array([[10, 21], [62, 33]], float)
arr2 = np.array([0, 0, 1], int)

# 1차원 방향으로 선택
print(arr1.take(arr2, axis=0))

# 2차원 방향으로 선택
print(arr1.take(arr2, axis=1))

[[10. 21.]
 [10. 21.]
 [62. 33.]]
[[10. 10. 21.]
 [62. 62. 33.]]


### 배열 수정 쿼리

In [ ]:
# 인덱스 배열로 쿼리
arr1 = np.zeros((2,2), float)
arr2 = np.array([1., 2.], float)
print arr1
print arr2
print arr1+arr2
print arr1 + arr2[np.newaxis,:]
print arr1 + arr2[:,np.newaxis]

[[ 0.  0.]
 [ 0.  0.]]
[ 1.  2.]
[[ 1.  2.]
 [ 1.  2.]]
[[ 1.  2.]
 [ 1.  2.]]
[[ 1.  1.]
 [ 2.  2.]]


## 선형대수 연산

## 행렬곱

In [ ]:
#linear algebra operations
X = np.arange(15).reshape((3, 5))
print(X)
print(X.T)
print(np.dot(X.T, X))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[125 140 155 170 185]
 [140 158 176 194 212]
 [155 176 197 218 239]
 [170 194 218 242 266]
 [185 212 239 266 293]]


### 벡터의 외적, 내적, 벡터곱

In [ ]:
arr1 = np.array([12, 43, 10], float)
arr2 = np.array([21, 42, 14], float)
print(np.outer(arr1, arr2))
print(np.inner(arr1, arr2))
print(np.cross(arr1, arr2))

[[ 252.  504.  168.]
 [ 903. 1806.  602.]
 [ 210.  420.  140.]]
2198.0
[ 182.   42. -399.]


### 행렬식, 역행렬

In [ ]:
# 행렬식
matrix = np.array([[74, 22, 10], [92, 31, 17], [21, 22, 12]], float)
print(matrix)
print(np.linalg.det(matrix))

# 역행렬
inv_matrix = np.linalg.inv(matrix)
print(inv_matrix)
print(np.dot(inv_matrix,matrix))

# 고윳값, 고유벡터
vals, vecs = np.linalg.eig(matrix)
print(vals)
print(vecs)

[[74. 22. 10.]
 [92. 31. 17.]
 [21. 22. 12.]]
-2852.000000000003
[[ 0.00070126  0.01542777 -0.02244039]
 [ 0.26192146 -0.23772791  0.11851332]
 [-0.48141655  0.4088359  -0.09467041]]
[[ 1.00000000e+00 -1.11022302e-16 -1.11022302e-16]
 [ 5.77315973e-15  1.00000000e+00  8.88178420e-16]
 [-3.91353616e-15 -1.05471187e-15  1.00000000e+00]]
[107.99587441  11.33411853  -2.32999294]
[[-0.57891525 -0.21517959  0.06319955]
 [-0.75804695  0.17632618 -0.58635713]
 [-0.30036971  0.96052424  0.80758352]]


### 통계 함수

In [ ]:
arr = np.random.rand(8, 4)
print(arr.mean())
print(np.mean(arr))
print(arr.sum())

0.5263198913707052
0.5263198913707052
16.842236523862567
